# Generated by Django 2.2.12 on 2025-04-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rearing_name', models.CharField(max_length=100)),
                ('initial_male_rabbits', models.IntegerField(default=0)),
                ('initial_female_rabbits', models.IntegerField(default=0)),
                ('initial_young_rabbits', models.IntegerField(default=0)),
                ('initial_baby_rabbits', models.IntegerField(default=0)),
                ('initial_food', models.FloatField(default=0)),
                ('initial_money', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.FloatField()),
                ('global_food', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('baby', 'Lapereau'), ('young', 'Jeune'), ('male', 'Mâle'), ('female', 'Femelle')], default='baby', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('food', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Cage')),
            ],
        ),
        migrations.CreateModel(
            name='GameDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_purchased', models.FloatField(default=0)),
                ('cages_purchased', models.IntegerField(default=0)),
                ('rabbits_sold_male', models.IntegerField(default=0)),
                ('rabbits_sold_female', models.IntegerField(default=0)),
                ('rabbits_sold_young', models.IntegerField(default=0)),
                ('rabbits_sold_baby', models.IntegerField(default=0)),
                ('turn_number', models.IntegerField(default=1)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.GameSetup')),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='rearing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Rearing'),
        ),
    ]
