# Generated by Django 2.2.12 on 2025-04-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rearing_name', models.CharField(max_length=100)),
                ('initial_male_rabbits', models.IntegerField(default=0)),
                ('initial_female_rabbits', models.IntegerField(default=0)),
                ('initial_young_rabbits', models.IntegerField(default=0)),
                ('initial_baby_rabbits', models.IntegerField(default=0)),
                ('initial_food', models.FloatField(default=0)),
                ('initial_money', models.FloatField(default=0)),
                ('initial_cages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rearing_name', models.CharField(max_length=20, unique=True)),
                ('current_money', models.FloatField(default=0)),
                ('current_food', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('baby', 'Lapereau'), ('young', 'Jeune'), ('male', 'Mâle'), ('female', 'Femelle')], default='baby', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('hunger', models.IntegerField(default=0)),
                ('infection', models.IntegerField(default=0)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('pregnancy_start', models.IntegerField(blank=True, null=True)),
                ('cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rabbits', to='jeu.Cage')),
                ('rearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to='jeu.Rearing')),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='rearing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='jeu.Rearing'),
        ),
    ]
