# Generated by Django 4.2 on 2025-04-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rearing',
            old_name='name',
            new_name='rearing_name',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='food',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='price',
        ),
        migrations.AddField(
            model_name='rabbit',
            name='hunger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='infection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='last_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='pregnancy_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='pregnancy_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rearing',
            name='current_food',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rearing',
            name='current_money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cage',
            name='cost',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='cage',
            name='rearing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='jeu.rearing'),
        ),
        migrations.DeleteModel(
            name='GameDashboard',
        ),
    ]
