# Generated by Django 4.2 on 2025-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_rename_name_rearing_rearing_name_remove_rabbit_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rearing',
            name='rearing_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
