# Generated by Django 2.2.12 on 2025-04-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_remove_rabbit_last_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rearing',
            name='global_food',
        ),
        migrations.RemoveField(
            model_name='rearing',
            name='money',
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to='jeu.Cage'),
        ),
    ]
